### PR TITLE
Fix issue #86

### PR DESCRIPTION
**Pull request by drmarconi**
Fixes issue #86 - app require parameter to require the exec creating the application pool.

### CODE REVIEW

**Comment by igalic** [comment]
we should do the version bumping in a separate commit / pr

**Comment by drmarconi** [comment]
ok, apologies for that. How should I proceed then? Revert version to previous values & submit new pr?

**Comment by jyaworski** [comment]
@drmarconi yes.

**Comment by drmarconi** [comment]
Thanks, changes made.

**Comment by igalic** [comment]
@drmarconi would you mind doing a squash?

**Comment by drmarconi** [comment]
Done :)

**Comment by jyaworski** [comment]
Merging, because this failure isn't due to you.

**Comment by drmarconi** [comment]
@jyaworski thanks, any change the Puppet Forge could be updated as well please? Just so I can pull down with r10k etc.

**Comment by jyaworski** [comment]
@drmarconi we do forge releases somewhat ad-hoc. I believe we're going to cut a forge release just before we merge the giant PR, but until then I would recommend referencing this commit in your Puppetfile.

**Pull request merged**
