### PR TITLE
Prepare for version 3.0.0

### PR DESCRIPTION
**Pull request by bbriggs**
The big thing in this version is a refactor of IIS sites and ending support for server 2008. 

Per @igalic's suggestion, we should wait for input from @WhatsARanjit for confirmation before releasing.

### CODE REVIEW

**Comment by WhatsARanjit** [comment]
@bbriggs How can I be of service?

**Comment by bastelfreak** [comment]
@WhatsARanjit wow thats fast! We're unsure if windows 2008 support got dropped during your refactor. this would require a module bump to 3.0. Otherwise a 2.1 release would be okay. Can you help us here?

**Comment by BarnumD** [comment]
In 2.0.2 (https://forge.puppet.com/puppet/iis/readme) site_id was listed as a parameter of iis::manage_site.  Is this still a valid parameter?  Can it be added to 3.0.0 readme?

Also, apppool_identitytype from iis::manage_app_pool.

**Comment by WhatsARanjit** [comment]
I coded in the `ConvertTo-Json` Powershell method to make stuff easier.  I remember being told this method was only available in a newer version of Powershell, so may not work on some versions of Windows unless Powershell is upgraded.

**Comment by bastelfreak** [comment]
@BarnumD thanks for noticing. Could you add a PR for that?

**Comment by BarnumD** [comment]
Sorry, I just don't think I have the time right now :(

**Comment by bbriggs** [comment]
I used the sneakernet to consult with him just now and he said he'd open up issues for those so a domain expert can work on them. In the mean time, I think we should hold off on this release (or maybe even close the PR).

**Comment by bbriggs** [comment]
@WhatsARanjit: So is the Powershell method the only thing that's blocking on server 2008? do you know of any other things that might cause support problems for that version?

**Comment by WhatsARanjit** [comment]
@bbriggs I'm not strictly a Windows person.  We'd have to flesh that stuff out with acceptance testing.  As far as my Windows-saavy colleagues, one thing they noticed was the use of the JSON method.

**Comment by bbriggs** [comment]
Thanks! We are getting our CI system set up for acceptance testing on this module now, so we should see soon what the deal is

-- Briggs

**Comment by petems** [comment]
WRT Json support, a similar issue was fixed by @matthewrstone in https://github.com/voxpupuli/puppet-windowsfeature/pull/58, changing the code explicitly to use csv over JSON. Could be possible for 2008R2 support?

**Comment by matthewrstone** [comment]
@petems I did some messing around with ConvertTo-Xml that turned into more messing around than I would have liked, but results are over here: https://github.com/matthewrstone/puppet-iis/tree/convert_to_xml

I ended up gutting quite a bit of the code so it made more sense for me, hence no PR, but the code is there for ConvertTo-XML if you want it.  If people are OK with the rest of the work, well, I've got like 2000 Windows servers I need to puppetize ASAP so getting a nice and shiny beefed up IIS module up and running sooner than later is something I can help with at least for the short term.

Side note - also added adding/modifying site id.  I needed that. Thx.

**Comment by rnelson0** [comment]
Bump for action. 2.0.2 on the forge, seems this is still needed but I'm not familiar enough to know if it should be merged or not.

**Comment by igalic** [comment]
i suggest a fresh modulesync and an actual release.

**Comment by bastelfreak** [comment]
@bbriggs can we merge this  + https://github.com/voxpupuli/puppet-iis/pull/176 and release 3.0.0?

**Comment by bbriggs** [comment]
Whoa, what a necrobump. I forgot this PR was even open.

**Pull request merged**
