### PR TITLE
manage_app_pool - add recycle logging control

### PR DESCRIPTION
**Pull request by lcoulson**
manage_app_pool - add recycle logging control

new param default undef for backward compatibility
logic in class handles undef

caller specify one or more values from
['Time','Requests','Schedule','IsapiUnhealthy','OnDemand','ConfigChange','PrivateMemory']

empty array [] will clear current logging on app pool (set to no logging)

### CODE REVIEW

**Comment by igalic** [comment]
@lcoulson this will need a docs update and i'd really like to see some spec tests for this!

**Comment by juniorsysadmin** [comment]
You'll need to drop the mixed case Puppet variables. Underscore variable names would be gooderific as well.

**Comment by lcoulson** [comment]
i'll fix this on Monday, I haven't any more strength today to battle rspec

**Comment by lcoulson** [comment]
@igalic @juniorsysadmin  - should be fixed now.  

Added tests, standardized variable naming, added example to doc.

note - inconsistent rules for Robocop between these test build plan thingys.  most recent required crazy ruby 'word array' constructor slang %w(foo bar) - others do not.

formatting in puppet class of split string on unless only way I've found to satisfy all test types for rspec, so yes that spit is flush against the hard left of the line.

**Pull request merged**
