### PR TITLE
manage_app_pool - add scheduled recycling control

### PR DESCRIPTION
**Pull request by lcoulson**
manage_app_pool - add scheduled recycling control

new param left undef default for backward compatibility
logic in class handles undef

caller provide array of time strings ['hh:mm:ss','...'] - empty array to
clear scheduled recycling on an app pool

### CODE REVIEW

**Comment by igalic** [comment]
@lcoulson this will need a docs update and i'd really like to see some spec tests for this!

**Comment by karmafeast** [comment]
I'm gonna do it for this and the others, have a cold... dxm fin for tomorrow

**Comment by juniorsysadmin** [comment]
Using underscores for the new long variables is also a good idea for readability.

**Comment by lcoulson** [comment]
@igalic @juniorsysadmin added tests, standardized varibles, added documentation etc.

**Pull request merged**
