### PR TITLE
idle action time set to undef

### PR DESCRIPTION
**Pull request by gigadafud**
Changing  the idle action timeout to undef and adding a trailing comma

### CODE REVIEW

**Comment by alexjfisher** [comment]
@gigadafud What's with the new PR?  Couldn't you have just updated https://github.com/voxpupuli/puppet-iis/pull/118 ?

**Comment by jyaworski** [comment]
@gigadafud lint is complaining. Can you fix that? Running puppet-lint -f over it should work for most of it.

**Comment by gigadafud** [comment]
Not exactly sure what it is failing on.  Throws me an error and basically a bunch of warnings.

ERROR: iis::manage_app_pool not in autoload module layout on line 1
WARNING: defined type not documented on line 1
WARNING: line has more than 80 characters on line 24

**Comment by jyaworski** [comment]
The travis log says:

```log
manifests/manage_app_pool.pp:160:trailing_whitespace:ERROR:trailing whitespace found
manifests/manage_app_pool.pp:161:trailing_whitespace:ERROR:trailing whitespace found
manifests/manage_app_pool.pp:18:variable_contains_upcase:WARNING:variable contains a capital letter
manifests/manage_app_pool.pp:162:variable_contains_upcase:WARNING:variable contains a capital letter
manifests/manage_app_pool.pp:163:variable_contains_upcase:WARNING:variable contains a capital letter
manifests/manage_app_pool.pp:165:variable_contains_upcase:WARNING:variable contains a capital letter
manifests/manage_app_pool.pp:167:variable_contains_upcase:WARNING:variable contains a capital letter
```

Once those are fixed we can continue.

**Comment by alexjfisher** [comment]
Closing in favour of https://github.com/voxpupuli/puppet-iis/pull/118

**Pull request closed without merging**
