### PR TITLE
Changed if statement to be an -Or command.

### PR DESCRIPTION
**Pull request by jwtdrjj**

### CODE REVIEW

**Comment by jwtdrjj** [comment]
This goes to issue #153

**Comment by igalic** [comment]
@jwtdrjj would you very much mind adding a spec test so we don't forget about this in the future?

**Comment by jwtdrjj** [comment]
will do

**Comment by igalic** [comment]
thank you @jwtdrjj!
if you need help, do not hesitate to bug us in #voxpupuli (freenode or https://puppetcommunity.slack.com/ )

**Comment by jwtdrjj** [comment]
I might, this was my first pull request to a module outside our company.   I've also never done a spec test, so this should be interesting.

**Comment by igalic** [comment]
thaaaaanks! \o/

**Comment by jwtdrjj** [comment]
Thank you

**Pull request merged**
