### PR TITLE
Fixed a casing issue

### PR DESCRIPTION
**Pull request by gigadafud**
Previously I have processmodel.idletimeoutaction and it was always trying to apply my changes when it saw a difference but it would never actually make the change.  I finally noticed that casing matters and it needs to be processmodel.idleTimeoutAction.  I corrected that as well as also added the check to test to see if the value was NOT undefined.

if $apppool_idle_timeout_action != undef

### CODE REVIEW

**Comment by bastelfreak** [comment]
hey @gigadafud, thanks for the PR! Could you please rebase against latest master?

**Comment by igalic** [comment]
it's deeply fascinating how quickly our prs become unmergable :P

**Comment by igalic** [comment]
@gigadafud it would also be good to add spect tests to cover this functionality

**Comment by petems** [comment]
Rebased in #145

**Pull request closed without merging**
