### PR TITLE
add Identity Process Model parameter

### PR DESCRIPTION
**Pull request by vprajapa**
Application Pool sometime need to be NetworkService instead of ApplicationPoolIdentity.

### CODE REVIEW

**Comment by ffrank** [comment]
Hi, thanks for this PR. Sorry it took so long to get back to you.

This looks good to me (although I will need feedback from someone familiar with IIS - @liamjbennett perhaps?)

@vprajapa do you think that you could add some tests for the new parameter? It's alright if not, we can do the legwork ourselves if necessary.

**Comment by jwatson3d** [comment]
The validation restriction in manage_app_pool.pp is restricting to a list of well-known hardcoded constants which does not allow for supplying either a local machine account or more likely a domain service account. This becomes important if the web application being installed will be accessing resources and services on other Windows nodes. The canonical use case would be using Windows integrated security to access a remote database server rather than being forced to use a named user account and password stored in a configuration file for the connection.

**Comment by jwatson3d** [comment]
This little snippet should do the trick:

  exec { "${appPoolName}-identity" :
    command   => "Import-Module WebAdministration; Set-ItemProperty \"IIS:\\AppPools\\${appPoolName}\" -name processModel -value @{userName=\"${appPoolDomain}\\${appPoolUserName}\";password=\"${appPoolPassword}\";identitytype=3}",
    logoutput => true,
    provider  => powershell,
    require   => [ Iis::Manage_app_pool[$appPoolName] ],
  }

**Comment by juniorsysadmin** [comment]
Superseded by #72

**Pull request closed without merging**
